[geometry]
gap-size=3
border-width=3

[behavior]
split-view-target=unfocused

[cursor]
theme=
size=24

[colors]
background=
focused-border=93a1a1
unfocused-border=586e75

[keybindings.wm]
reload-config=super+shift+r

[keybindings.output]
cycle-prev=super+comma
cycle-next=super+period

[keybindings.workspace]
cycle-next=super+j
cycle-prev=super+k
add-next=super+ctrl+j
add-prev=super+ctrl+k
move-to-prev-output=super+shift+comma
move-to-next-output=super+shift+period

[keybindings.panel]
cycle-prev=super+h
cycle-next=super+l
add-prev=super+ctrl+h
add-next=super+ctrl+l
move-to-next-workspace=super+shift+j
move-to-prev-workspace=super+shift+k
move-to-next-new-workspace=super+ctrl+shift+j
move-to-prev-new-workspace=super+ctrl+shift+k
toggle-split-view=super+semicolon

[keybindings.window]
cycle-next=super+m
cycle-prev=super+n

; 使わないが、提示資料では無効化方法が確認できないため退避
move-next=super+alt+shift+m
move-prev=super+alt+shift+n

move-to-prev-panel=super+shift+h
move-to-next-panel=super+shift+l
move-to-prev-new-panel=super+ctrl+shift+n
move-to-next-new-panel=super+ctrl+shift+m

toggle-fullscreen=super+f
close=super+q

[keybindings.spawn]
foot=super+enter
~/.local/bin/wofi-drun=super+space
/home/odara/.local/bin/lock=super+m
/home/odara/.local/bin/lock-and-suspend=super+r
/home/odara/.local/bin/screenshot-copy=super+p
/home/odara/.local/bin/screenshot-save=super+shift+p
/home/odara/.local/bin/volume-up=XF86AudioRaiseVolume
/home/odara/.local/bin/volume-down=XF86AudioLowerVolume
/home/odara/.local/bin/volume-mute=XF86AudioMute
/home/odara/.local/bin/mic-mute=XF86AudioMicMute
/home/odara/.local/bin/brightness-up=XF86MonBrightnessUp
/home/odara/.local/bin/brightness-down=XF86MonBrightnessDown
