[geometry]
gap-size=8
border-width=4

[behavior]
split-view-target=unfocused

[cursor]
theme=Adwaita
size=32

[colors]
background=
focused-border=93a1a1
unfocused-border=586e75

[keybindings.wm]
reload-config=super+shift+r

[keybindings.output]
cycle-prev=super+comma
cycle-next=super+period

[keybindings.workspace]
cycle-next=super+j
cycle-prev=super+k
add-next=super+alt+j
add-prev=super+alt+k
move-to-prev-output=super+shift+comma
move-to-next-output=super+shift+period

[keybindings.panel]
cycle-prev=super+h
cycle-next=super+l
add-prev=super+alt+h
add-next=super+alt+l
move-to-next-workspace=super+shift+j
move-to-prev-workspace=super+shift+k
move-to-next-new-workspace=super+alt+shift+j
move-to-prev-new-workspace=super+alt+shift+k
toggle-split-view=super+semicolon

[keybindings.window]
cycle-next=super+m
cycle-prev=super+n

; 使わないが、提示資料では無効化方法が確認できないため退避
move-next=super+alt+shift+m
move-prev=super+alt+shift+n

move-to-prev-panel=super+shift+h
move-to-next-panel=super+shift+l
move-to-prev-new-panel=super+alt+shift+h
move-to-next-new-panel=super+alt+shift+l

toggle-fullscreen=super+f
close=super+q

[keybindings.spawn]
foot=super+enter
fuzzel=super+space
/home/odara/.local/bin/wayland-session-exit=super+escape
/home/odara/.local/bin/lock=super+e
/home/odara/.local/bin/lock-and-suspend=super+r
/home/odara/.local/bin/screenshot-copy=super+p
/home/odara/.local/bin/screenshot-save=super+shift+p
/home/odara/.local/bin/wob-volume 5%+=XF86AudioRaiseVolume
/home/odara/.local/bin/wob-volume 5%-=XF86AudioLowerVolume
wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle=XF86AudioMute
wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle=XF86AudioMicMute
/home/odara/.local/bin/brightness-wob 5%+=XF86MonBrightnessUp
/home/odara/.local/bin/brightness-wob 5%-=XF86MonBrightnessDown
