#!/bin/sh
set -eu

export XCURSOR_THEME="${XCURSOR_THEME:-Adwaita}"
export XCURSOR_SIZE="${XCURSOR_SIZE:-32}"

"$HOME/.local/bin/wayland-session-init"
"$HOME/.local/bin/wm-launch" &
wm_pid=$!

if [ -f "$HOME/medias/frieren.png" ]; then
  # Defer wallpaper startup until after the WM launcher has spawned the WM.
  sleep 0.2
  swaybg -m fill -i "$HOME/medias/frieren.png" &
fi

wait "$wm_pid"
