set -g status-style bg=#d98277,fg=#000000


set -g pane-active-border-style fg=#d98277


# prefix + q などで出る pane 番号表示
set -g display-panes-colour "#ffffff"
set -g display-panes-active-colour "#d98277"



set -g window-status-style bg=#d98277,fg=#000000
set -g window-status-current-style bg=#000000,fg=#d98277
