XMODIFIERS=@im=fcitx
MOZ_ENABLE_WAYLAND='1 firefox'
QT_QPA_PLATFORM=WAYLAND
EDITOR=vim

SSH_AGENT_PID=""
SSH_AUTH_SOCK=${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent.ssh

PASSWORD_STORE_CHARACTER_SET=[:alnum:]!
PASSWORD_STORE_GENERATED_LENGTH=22
PASSWORD_STORE_CLIP_TIME=10

PAGER=less
LESS='-iMR --mouse'

