# Created by newuser for 5.9
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

autoload -Uz compinit
compinit

autoload -Uz promptinit
promptinit

eval "$(starship init zsh)"

GPG_TTY=$(tty)
export GPG_TTY

export $(envsubst < ~/.env)

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

