#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: wait-for-children.sh --run-id ID [--run-id ID ...] [options]

Block until one or more tmux children finish, then print a JSON summary.

Options:
  --run-id ID          A child run-id to wait for (repeatable).
  --agents-dir DIR     Path to .agents directory (default: ./.agents).
  --timeout SECONDS    Total poll timeout across all children, default 600.
  --poll SECONDS       Poll interval in seconds, default 3.
  --help               Show this help.

Exit codes:
  0   All children succeeded.
  1   One or more children failed or timed out.
  3   Usage or input error.
USAGE
}

die() {
  printf 'wait-for-children: %s\n' "$*" >&2
  exit 3
}

run_ids=()
agents_dir=
poll_timeout=600
poll_interval=3

while [[ $# -gt 0 ]]; do
  case "$1" in
    --run-id)       run_ids+=("$2"); shift 2 ;;
    --agents-dir)   agents_dir=$2; shift 2 ;;
    --timeout)      poll_timeout=$2; shift 2 ;;
    --poll)         poll_interval=$2; shift 2 ;;
    --help)         usage; exit 0 ;;
    *)              die "unknown argument: $1" ;;
  esac
done

((${#run_ids[@]} > 0)) || die "at least one --run-id is required"
[[ "$poll_timeout"  =~ ^[0-9]+$ ]] || die "--timeout must be a non-negative integer"
[[ "$poll_interval" =~ ^[0-9]+$ ]] || die "--poll must be a non-negative integer"
(( poll_timeout > 0 )) || die "--timeout must be greater than zero"
(( poll_interval > 0 )) || die "--poll must be greater than zero"

agents_dir=${agents_dir:-.agents}
[[ -d "$agents_dir" ]] || die "agents directory not found: $agents_dir"
agents_dir=$(cd "$agents_dir" && pwd -P)

status_dir="$agents_dir/status"

# -- Pre-check and read artifact_path from each status JSON for the summary.
#    Fail fast if any status JSON is missing.
declare -A artifacts
for run_id in "${run_ids[@]}"; do
  sf="$status_dir/$run_id.json"
  [[ -f "$sf" ]] || die "status JSON not found for run-id: $run_id"
  # Assumes one JSON field per line (generated by write_status). A full
  # parser (jq) would be more robust but adds a hard dependency.
  raw=$(sed -n 's/.*"artifact_path": *"\([^"]*\)".*/\1/p;T;q' "$sf")
  artifacts["$run_id"]=${raw:-}
done

# -- Poll loop ---------------------------------------------------------------
declare -A results   # run-id -> "waiting"|"success"|"failure"
for run_id in "${run_ids[@]}"; do
  results["$run_id"]="waiting"
done

remaining=${#run_ids[@]}
start_sec=$SECONDS

while (( remaining > 0 && SECONDS - start_sec < poll_timeout )); do
  for run_id in "${run_ids[@]}"; do
    [[ "${results[$run_id]}" != "waiting" ]] && continue
    if [[ -f "$status_dir/$run_id.success" ]]; then
      results["$run_id"]="success"
      (( remaining-- ))
    elif [[ -f "$status_dir/$run_id.failure" ]]; then
      results["$run_id"]="failure"
      (( remaining-- ))
    fi
  done
  if (( remaining > 0 )); then
    sleep "$poll_interval"
  fi
done

elapsed=$(( SECONDS - start_sec ))

for run_id in "${run_ids[@]}"; do
  if [[ "${results[$run_id]}" == "waiting" ]]; then
    results["$run_id"]="timeout"
  fi
done

# -- Summary JSON ------------------------------------------------------------
overall="success"
success_count=0
failure_count=0
timeout_count=0
for run_id in "${run_ids[@]}"; do
  case "${results[$run_id]}" in
    success) (( success_count += 1 )) ;;
    failure) (( failure_count += 1 )); overall="failure" ;;
    timeout) (( timeout_count += 1 )); overall="failure" ;;
  esac
done

# Write JSON to stdout for easy consumption by Pi / calling scripts.
json_escape() {
  local value=${1-}
  value=${value//\\/\\\\}
  value=${value//\"/\\\"}
  value=${value//$'\n'/\\n}
  value=${value//$'\r'/\\r}
  value=${value//$'\t'/\\t}
  printf '%s' "$value"
}

printf '{\n'
printf '  "overall": "%s",\n' "$(json_escape "$overall")"
printf '  "total": %d,\n' "${#run_ids[@]}"
printf '  "success": %d,\n' "$success_count"
printf '  "failure": %d,\n' "$failure_count"
printf '  "timeout": %d,\n' "$timeout_count"
printf '  "poll_elapsed_seconds": %d,\n' "$elapsed"
printf '  "children": {\n'
first=true
for run_id in "${run_ids[@]}"; do
  $first || printf ',\n'
  first=false
  printf '    "%s": {\n' "$(json_escape "$run_id")"
  printf '      "status": "%s",\n' "$(json_escape "${results[$run_id]}")"
  printf '      "artifact_path": "%s"\n' "$(json_escape "${artifacts[$run_id]-}")"
  printf '    }'
done
printf '\n  }\n'
printf '}\n'

case "$overall" in
  success) exit 0 ;;
  *)       exit 1 ;;
esac
