set -g mouse on
setw -g alternate-screen on
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

#bind c new-window -c '#{pane_current_path}'
#bind '"' split-window -vc '#{pane_current_path}'
#bind % split-window -hc '#{pane_current_path}'

set-option -g default-terminal "tmux-256color" # 基本的にはscreen-256colorかtmux-256colorを設定
set-option -ga terminal-overrides ",$TERM:Tc" # tmuxを起動していない時のzshでの$TERMの値を指定

set -g set-clipboard on #OSC52によるクリップボードの書き込みを許可
